# Rubocop version 0.56.0
#
# Run this command to try Rubocop.
#     -a: Fix automaticly all smells they could solve
#     -D: Show cop names
#     -S: Show URL style guide to solve this smell
#
# bundle exec rubocop -a -D -S

# Run this command to add Rubocop offenses at .rubocop_todo.yml. With this, this offenses
# will be ignored at future inspections, but only to fix them later.
# rubocop --auto-gen-config
# Them, check .rubocop_todo.yml file.

# Use this command commented at top of files to skip some or all Rubocop tests.
# Disable all cops example
# rubocop:disable all
# rubocop:enable all

# Visit http://www.rubydoc.info/gems/rubocop/RuboCop/Cop for more options and info.

# inherit_from: .rubocop_todo.yml

# Add files which you don't want Rubocop will check.

AllCops:
  TargetRubyVersion: 2.4.0
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - Gemfile
    - Guardfile
    - Capfile
    - infraestructure/**/*
    - script/**/*
    - 'node_modules/*'
    - 'vendor/**/*'
    - lib/tasks/**/*
    - lib/capistrano/**/*
    - lib/importations/**/*
    - spec/**/*
    - features/**/*
    - db/**/*
    - bin/**/*
    - config/**/*

Documentation:
  Enabled: false

Rails:
  Enabled: true
Rails/TimeZone:
  Enabled: false
Rails/Date:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
Style/SignalException:
  EnforcedStyle: only_raise
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'
Style/ModuleFunction:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/NestedModifier:
  Enabled: false

Metrics/LineLength:
  Max: 90


